### ISSUE TITLE
Add REST API so data can be accessed by ChatGPT plugin system

### ISSUE THREAD

**Issue by andrewgazelka** [embassy-rs/stm32-data#184]
I speak about this some [here](https://andrew.tech/gpt4-hals-and-rest-libs).

I think this would be potentially very very useful. Probably going to do myself unless you think you want this in your repo.

**Comment by Dirbaio** [comment]
generated json output is now automatically uploaded to https://github.com/embassy-rs/stm32-data-generated/

so you can now access it with the raw data github api: https://raw.githubusercontent.com/embassy-rs/stm32-data-generated/main/data/chips/STM32C031C4.json

beyond that, maintaining and hosting a "real" JSON REST API is somewhat out of scope of this project.
