### ISSUE TITLE
STM32H7 DAC is a new variant

### ISSUE THREAD

**Issue by adamgreig** [embassy-rs/stm32-data#222]
Currently there's a V1 and V2 DAC and the H7 is set to use V1. Unfortunately it seems it's really a similar but different "V3" evolved from V2, with changes in TSEL, TEN, and BOFF, plus the new CEN field from V2:

V1 (from STM32F4 RM0090):
![image](https://github.com/embassy-rs/stm32-data/assets/47219/59d1852d-801d-42c2-afe5-b1087232110e)

STM32H745 reference manual RM0399:
![image](https://github.com/embassy-rs/stm32-data/assets/47219/9cd78912-b8f7-4895-93c5-d552720b8e3c)

Additionally the TSEL enum is changed:

V1:
![image](https://github.com/embassy-rs/stm32-data/assets/47219/1221b18d-2bc8-4dfa-b669-33bb4fe09300)

STM32H745:
![image](https://github.com/embassy-rs/stm32-data/assets/47219/2acc29dc-8615-4c86-91a3-ae418206ecde)
![image](https://github.com/embassy-rs/stm32-data/assets/47219/be5e440b-be56-472d-9778-bd56a32b42f3)

**Comment by JuliDi** [comment]
Just as a note regarding the STM32H7: For the H7A3/B3/B0 variants, there is also RM0455 which may or may not contain differences to RM0399 (I didn't spot any for the aforementioned registers, though).

**Comment by JuliDi** [comment]
The [version spreadsheet ](https://docs.google.com/spreadsheets/d/1-R-AjYrMLL2_623G-AFN2A9THMf8FFMpFD4Kq-owPmI/edit#gid=1972450814)would probably need to be corrected, as well, to reflect the "version bump" to v3.
