### ISSUE TITLE
STM32U5 is compatible with CRS v1 but CRS registers are not generated for U5 chips

### ISSUE THREAD

**Issue by tyler-gilbert** [embassy-rs/stm32-data#225]
I am new to embassy, but from what I can tell, there just needs to be another line added to `chips.rs` here specifying to use `("STM32G4.*:CRS:.*", ("crs", "v1", "CRS"))`.

```
            ("STM32G0B1.*:CRS:.*", ("crs", "v1", "CRS")),
            ("STM32G0C1.*:CRS:.*", ("crs", "v1", "CRS")),
            ("STM32G4.*:CRS:.*", ("crs", "v1", "CRS")),
```

Does that seem like the right solution?

**Comment by Dirbaio** [comment]
If the registers are indeed identical yes, that's the right fix. Can you send a PR?

**Comment by tyler-gilbert** [comment]
I will send a PR.
