### ISSUE TITLE
STM32G474CB Missing Quad SPI peripheral

### ISSUE THREAD

**Issue by Tupelov** [embassy-rs/stm32-data#293]
For whatever reason, the generater only outputs the qspi interrupt but not the actual peripheral itself.

**Comment by xoviat** [comment]
looks like we don't have an implementation for that version at all, so it will need to be added

**Comment by Tupelov** [comment]
> looks like we don't have an implementation for that version at all, so it will need to be added

I've tried various times to create a v4 version of the peripheral but for whatever reason it won't show up in the output. From what I could tell, only the bit width of a single register was changed and to my knowledge they changed the name of the qspi enable register but even after modifying the RCC yaml, I couldn't get it to work.
Could there be something else besides the chips.rs and quadspi_v4.yaml that I need to edit?

**Comment by dlaw** [comment]
I just used quadspi via stm32-metapac on STM32G473, so I can confirm that #311 fixed this issue and this issue can be closed.
