### ISSUE TITLE
Incorrect memory sizes tracking issue

### ISSUE THREAD

**Issue by Dirbaio** [embassy-rs/stm32-data#301]
If you've got a chip where the `stm32-metapac/memory.x` feature generates a wrong memory.x please post here.

Identified cases:

- STM32G030K8 flash generates 32kb but has 64kb
- STM32WL55JC ram generates 12kb but has 64kb

**Comment by TaylorCarpenter** [comment]
STM32WB55VG ram generates 128kb but has 192kb.

**Comment by phycrax** [comment]
STM32G030C8 flash generates 32kb but has 64kb

**Comment by trepidacious** [comment]
stm32g491re memory.x shows 32kb RAM, chip should have 112kb (3 blocks of 80, 16, 16)

**Comment by Dirbaio** [comment]
STM32F303ZE says it has 64k but only has 48kb https://github.com/embassy-rs/stm32-data-generated/issues/1
stm32u5a5zj says it has 32k but it has 2.5mb or something

**Comment by eZioPan** [comment]
STM32F411RE:

| Type | memory.x | DS Tab.2  | Note |
|------| -------- | --------- | ---- |
| RAM  |   64K    |  128 KB   |      |

**Comment by eZioPan** [comment]
|     Chip         |  Type  | memory.x | DS Tab.2               |        Note        |
| :--------------: | :----: | :------: | :--------------------: | :----------------: |
|  STM32H5[67]xxG  |  RAM   |  256 K   |  640 (256+64+320) KB   |                    |
|  STM32H5[67]xxI  |  RAM   |  256 K   |  640 (256+64+320) KB   |                    |

**Comment by Dirbaio** [comment]
|     Chip    |  Type  | memory.x | actual  |        Note        |
| :---------: | :----: | :------: | :-------: | :----------------: |
| STM32F051R8T6 |  RAM   |  7 K   |  8 KB   |   #437         |

**Comment by LorenzoCucchi** [comment]
|     Chip    | Type | memory.x | actual | Note |
|:-----------:|:----:|:--------:|:------:|:----:|
| STM32F756ZG |  RAM |   320K   |  256K  |      |

64 K less since DTCM starting at 0x20000000 is not used, and RAM starts at 0x20010000.

**Comment by adri326** [comment]
|     Chip    |  Type  | memory.x | DS Tab.2  |        Note        |
| :---------: | :----: | :------: | :-------: | :----------------: |
| STM32L4A6ZG |  RAM   |  320K   |  256K   |                    |

Opposite issue to the one above: `SRAM` correctly starts at `0x2000_0000` up through `0x2004_0000`, but the last `64K` aren't available. According to the doc, there's a second `SRAM2` memory device with `64K` size, mapped *both* to `0x1000_0000` (which is present in the generated `STM32L4A6ZG.json`, although it has size 0), and to `0x2004_0000`

**Comment by spcan** [comment]
STM32F746ZG variant presents the same issue as the STM32F756 variant described before in this thread.

| Chip         | Type     | memory.x | Actual | Note
|--------------|-----------|:------------:|:--------:|--------|
| STM32F746ZG | RAM      |  320K        |  256K |    |

64K less because DTCM should not be counted. RAM starts at 0x20010000 not at 0x20000000.

Consider separating SRAM1 (240K) and SRAM2 (16K).

**Comment by wagcampbell** [comment]
As mentioned in the Matrix chat, seeing some incorrect sizes for the STM32U5 Family.

From the reference manual (RM0456):

Flash configuration:
RM0456, 7.3.1, Table 51., 52., 53.:
![image](https://github.com/embassy-rs/stm32-data/assets/49646556/6fad7ad7-9ce5-474c-84de-3079c340f9e7)
![image](https://github.com/embassy-rs/stm32-data/assets/49646556/184ac572-ba6f-48e1-877e-d5b3ab5d1841)
![image](https://github.com/embassy-rs/stm32-data/assets/49646556/f895fb3d-2a59-43ff-a97f-2290f596bb9b)

SRAM configuration:
RM0456, 6.3.1, Table 45
![image](https://github.com/embassy-rs/stm32-data/assets/49646556/b867a3a0-6f88-43f4-9f7d-ed86c743b932)

Also, from the product page:
![image](https://github.com/embassy-rs/stm32-data/assets/49646556/651b1e16-32f8-49c6-b8b5-3f428a09e7b1)
![image](https://github.com/embassy-rs/stm32-data/assets/49646556/ca717f71-04d1-409e-b0e9-2fd6944151ee)
![image](https://github.com/embassy-rs/stm32-data/assets/49646556/29a44edb-cacf-4f4e-aca1-211a2bcb4f53)
![image](https://github.com/embassy-rs/stm32-data/assets/49646556/f1315f60-1453-432e-b4b7-8f23a4740386)
![image](https://github.com/embassy-rs/stm32-data/assets/49646556/ec35aa11-f35c-4cfb-9600-20961b63de03)
![image](https://github.com/embassy-rs/stm32-data/assets/49646556/aca218e0-7800-42f8-b5b8-7f33fb71b926)

I haven't studied other STM32 MCUs this closely, but is it unusual to have so many SRAM devices?
> Up to seven SRAMs are embedded in the devices

I'm working on a fix, but thought I'd post this before getting ahead of myself.

**Comment by Dirbaio** [comment]
https://github.com/embassy-rs/stm32-data/commit/3eab5e1161312efc394d2a238ba8b93e174846a1 fixes all issues reported here and more. I believe all stm32 memory maps are correct now.
