### ISSUE TITLE
STM32G4: ADC sample times are incorrect

### ISSUE THREAD

**Issue by dlaw** [embassy-rs/stm32-data#448]
Actual:
![2024-04-03-153129_983x836_scrot](https://github.com/embassy-rs/stm32-data/assets/606010/44ff5475-a1d8-4642-9a9a-ca6af4cfe974)

stm32-data:
![2024-04-03-153146_857x467_scrot](https://github.com/embassy-rs/stm32-data/assets/606010/fa3e0d23-8794-4a77-a2c6-630dedac1313)

**Comment by qff233** [comment]
yes! I mention it in #440 also!

**Comment by dlaw** [comment]
Fixed in https://github.com/embassy-rs/stm32-data/commit/9dfb42cd915a1102dffaf346a4f41e4c424638c3
*Thank you!!!*
