### ISSUE TITLE
Missing "kind": "adc" for STM32H533RE

### ISSUE THREAD

**Issue by dgehriger** [embassy-rs/stm32-data#477]
The STM32H533RE.json correctly lists `ADC1`, but I believe it's missing the entry `"kind": "adc"`. This in turn causes embassy-stm32 to not include the ADC module.

**Comment by Dirbaio** [comment]
To fix this, you'll have to go through [these steps](https://github.com/embassy-rs/stm32-data?tab=readme-ov-file#adding-support-for-a-new-peripheral). First check whether the yaml is equal to one of the existing versions (take into account there might be "false" differences, like something being one array in one and N fields in the other). If not, then add a new version.
