### ISSUE TITLE
Suspicious Memory layout for STM32G4

### ISSUE THREAD

**Issue by AdinAck** [embassy-rs/stm32-data#479]
As outlined in #478 , the SRAM size for these chips looks wrong. But I am not sure how to correct it.

<img width="684" alt="image" src="https://github.com/embassy-rs/stm32-data/assets/30732255/5c2fce9d-13ec-4f04-aa1a-14c0d929f482">

**Comment by Dirbaio** [comment]
If the ram is aliased, just put it twice. Something like this should work:

`CCM_SRAM_ICODE 0x10000000 10, SRAM1 0x20000000 16, SRAM2 0x20004000 6, CCM_SRAM_DCODE 0x20005800 10`

The memory.x generator will use the largest contiguous block, in this case 32kb stating at 0x20000000.

**Comment by AdinAck** [comment]
Gotcha, on it.

**Comment by AdinAck** [comment]
I have amended and reopened #478 . I don't have the other variants of the G4 so I can't test the new memory layouts and as such I did not fix those.

**Comment by AdinAck** [comment]
<img width="687" alt="image" src="https://github.com/embassy-rs/stm32-data/assets/30732255/786a28f8-a215-49c0-b790-155fe151f056">

Surely this is a typo in the G441xB datasheet 🤣
