### ISSUE TITLE
Memory layout wrong for F746NG

### ISSUE THREAD

**Issue by ProfFan** [embassy-rs/stm32-data#491]
```
MEMORY
{
    FLASH	(rx)	: ORIGIN = 0x8000000,	LENGTH = 1024K
    RAM	(rwx)	: ORIGIN = 0x20000000,	LENGTH = 320K
}
```
from official linker file https://github.com/wowawhite/TouchGFX_Simulator/blob/master/TouchGFX_Simulator/STM32F746NGHX_RAM.ld

**Comment by Dirbaio** [comment]
this was fixed in 3eab5e1161312efc394d2a238ba8b93e174846a1 , see  #301 

this is the generated memory map now https://github.com/embassy-rs/stm32-data-generated/blob/main/stm32-metapac/src/chips/stm32f746ng/memory_x/memory.x

which is correct
