### ISSUE TITLE
FMC/LTDC/etc missing for stm32f746ng

### ISSUE THREAD

**Issue by ProfFan** [embassy-rs/stm32-data#492]
Actually I think a lot of peripherals are missing for the F7 series, they exist in `embassy-stm32` only for very small number of devices such as `stm32f767ii`...

**Comment by ProfFan** [comment]
I think this is due to the LTDC being a "lcdtft1_v1_0" not "v1_1"

**Comment by Dirbaio** [comment]
can you
- verify LTDC registers for this chip are indeed the same between the Reference Manual and ltdc_v1.yaml
- send a PR adding more rows here https://github.com/embassy-rs/stm32-data/blob/main/stm32-data-gen/src/chips.rs#L273
?

**Comment by ProfFan** [comment]
Check the RM, registers are the same, let me make a PR.

**Comment by ProfFan** [comment]
Thanks @Dirbaio !
