### ISSUE TITLE
Missing register definitions for configuring USB OTG HS PHY (only for STM32U59x/5Ax/5Fx/5Gx)

### ISSUE THREAD

**Issue by wagcampbell** [embassy-rs/stm32-data#519]
I'm running into some issues getting USB OTG working for an STM32U59x part.

Unlike the other STM32U5 parts, there are a some additional steps required to configure this USB OTG HS for STM32U59x/5Ax/5Fx/5Gx.
![image](https://github.com/user-attachments/assets/1dfd7771-c627-4c95-b021-f4eefd10e855)
![image](https://github.com/user-attachments/assets/30a33eb9-471a-4143-8359-d3558d6d5d5c)
![image](https://github.com/user-attachments/assets/cd214887-6d4d-41e5-a84b-c1f0a948b189)

The stm32 hal is missing some register definitions:
![image](https://github.com/user-attachments/assets/822fea77-7e42-4b5e-b757-0e152bfebec1)
![image](https://github.com/user-attachments/assets/7387a82f-e9c5-41a9-a388-321c09289e56)
![image](https://github.com/user-attachments/assets/16a15b04-0f8f-4f82-8d1f-98b5cadb1ba3)

Also, while the OTG_FS and OTG_HS control and status registers (CSRs) are mostly the same, there are some differences.
Based on what I've gathered, I expect this will mean a change to the embassy-usb-synopsys-otg crate.

I haven't been able to successfully get this working yet, so there may be some additional steps/changes.

Hopefully, I can manage to get this working and can follow up with more details.

**Comment by MDr164** [comment]
I added the missing register definitions and added the extra clock to rcc. Last two bits are the setup sequence for these chips and potentially an addition to the synopsys otg crate. I'll try getting to that and testing on hardware (I got an STM32U5A5 for that) rather sooner then later.
