### ISSUE TITLE
Windows Builds seems to be broken

### ISSUE THREAD

**Issue by taylorh140** [embassy-rs/stm32-data#528]
To reproduce grab the present main and build on a window machine.
![image](https://github.com/user-attachments/assets/9ba8ded9-289a-4735-9cc7-c2a1a9a63011)
You should get this error. It has something to do with the fmt ? maybe? 

STATUS_STACK_BUFFER_OVERRUN

seems bad.

Might be relevent:
https://users.rust-lang.org/t/status-stack-buffer-overrun/34873

It would match the story about the "println(...{:?}..., something);" causing issues. as fmt seems to be at the root of the call stack.

**Comment by taylorh140** [comment]
So I took the folder from windows after d.ps1 executed and moved it to my linux setup. And got the same problem. So this is actually probably a problem with the d.ps1 and maybe not with the rust code.

**Comment by brunob45** [comment]
./d.ps1 is pulling embassy-rs/stm32-data-sources@74b97817d4c4ed0db9d19a8eac46720b3c5b0d57 (April 12) but

./d is pulling embassy-rs/stm32-data-sources@709c1060ac2ec57f6042f2b4eb9cf8c1821a6c57 (April 29)

Manually pulling embassy-rs/stm32-data-sources@709c1060ac2ec57f6042f2b4eb9cf8c1821a6c57 or embassy-rs/stm32-data-sources@1a3751550575f8ffee5e45307713a3e08bc9ffb4 (Jun 7) fixes the build.

**Comment by taylorh140** [comment]
This is good advice.
